/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['IBM Plex Sans', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        navy: {
          /* Blu istituzionale #004587 — RGB 0, 69, 135; secondario #003366 */
          50: '#E6EEF5',
          100: '#CCDDEB',
          200: '#99BBD7',
          300: '#6699C3',
          400: '#3377AF',
          500: '#1A639B',
          600: '#004587',
          700: '#003366',
          800: '#002952',
          900: '#001F3D',
          950: '#000F1F',
        },
        gold: {
          50: '#FBF6E5',
          100: '#F5E9BB',
          200: '#ECD679',
          300: '#E2C347',
          400: '#D4AF37',
          500: '#B5952F',
          600: '#8E7424',
          700: '#67541A',
          800: '#403511',
          900: '#191507',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'ds-sm': 'var(--ds-radius-sm)',
        'ds-md': 'var(--ds-radius-md)',
        'ds-lg': 'var(--ds-radius-lg)',
        'ds-xl': 'var(--ds-radius-xl)',
      },
      fontSize: {
        'ds-page': ['var(--ds-text-page)', { lineHeight: 'var(--ds-leading-tight)', fontWeight: '700' }],
        'ds-page-lg': ['var(--ds-text-page-lg)', { lineHeight: 'var(--ds-leading-tight)', fontWeight: '700' }],
        'ds-hero': ['var(--ds-text-hero)', { lineHeight: '1.05', fontWeight: '700', letterSpacing: '-0.025em' }],
        'ds-hero-sm': ['var(--ds-text-hero-sm)', { lineHeight: '1.05', fontWeight: '700', letterSpacing: '-0.025em' }],
        'ds-hero-lg': ['var(--ds-text-hero-lg)', { lineHeight: '1.05', fontWeight: '700', letterSpacing: '-0.025em' }],
        'ds-cta': ['var(--ds-text-cta)', { lineHeight: '1.1', fontWeight: '700' }],
        'ds-cta-md': ['var(--ds-text-cta-md)', { lineHeight: '1.1', fontWeight: '700' }],
        'ds-cta-lg': ['var(--ds-text-cta-lg)', { lineHeight: '1.1', fontWeight: '700' }],
        'ds-section': ['var(--ds-text-section)', { lineHeight: 'var(--ds-leading-tight)', fontWeight: '700' }],
        'ds-section-lg': ['var(--ds-text-section-lg)', { lineHeight: 'var(--ds-leading-tight)', fontWeight: '700' }],
        'ds-subsection': ['var(--ds-text-subsection)', { lineHeight: 'var(--ds-leading-snug)', fontWeight: '700' }],
        'ds-subsection-lg': ['var(--ds-text-subsection-lg)', { lineHeight: 'var(--ds-leading-snug)', fontWeight: '700' }],
        'ds-card': ['var(--ds-text-card)', { lineHeight: 'var(--ds-leading-snug)', fontWeight: '600' }],
        'ds-body': ['var(--ds-text-body)', { lineHeight: 'var(--ds-leading-body)' }],
        'ds-small': ['var(--ds-text-small)', { lineHeight: 'var(--ds-leading-body)' }],
        'ds-caption': ['var(--ds-text-caption)', { lineHeight: 'var(--ds-leading-body)' }],
      },
      spacing: {
        'ds-section-y': 'var(--ds-section-py)',
        'ds-section-y-lg': 'var(--ds-section-py-lg)',
        'ds-card': 'var(--ds-card-padding)',
        'ds-card-lg': 'var(--ds-card-padding-lg)',
        'ds-grid': 'var(--ds-grid-gap)',
        'ds-btn': 'var(--ds-btn-height)',
        'ds-btn-sm': 'var(--ds-btn-height-sm)',
        'ds-btn-xs': 'var(--ds-btn-height-xs)',
      },
      boxShadow: {
        'ds-sm': 'var(--ds-shadow-sm)',
        'ds-md': 'var(--ds-shadow-md)',
        'ds-lift': 'var(--ds-shadow-lift)',
        'ds-primary': 'var(--ds-shadow-primary)',
        'ds-primary-hover': 'var(--ds-shadow-primary-hover)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-up': 'fade-up 0.6s ease-out forwards',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
