"""Testo ufficiale pagina Chi siamo."""

CHI_SIAMO_SUMMARY = (
    "Storia e identità della Sezione AIA di Legnano, dal 1927 al servizio del calcio e della comunità arbitrale."
)

CHI_SIAMO_BODY_HTML = """
<p>L'Associazione Italiana Arbitri (AIA), fondata a Milano il 27 agosto 1911, è l'organismo che riunisce tutti gli arbitri di calcio italiani all'interno della FIGC. Oggi l'AIA è strutturata in 18 Comitati Regionali, 2 Comitati Provinciali Autonomi e 209 Sezioni distribuite su tutto il territorio nazionale, autentico cuore pulsante del sistema arbitrale.</p>
<p>La <strong>Sezione di Legnano</strong> affonda le sue radici proprio in quella storia gloriosa. Nasce nel 1927 come sottosezione di Milano, e da allora non ha mai smesso di crescere e trasformarsi insieme alla città. Dai primi, angusti locali in piazza Trento e Trieste, la nostra sede ha cambiato più volte volto e indirizzo, seguendo il passo della comunità: dal Dopolavoro Dell'Acqua in via Cuttica al Caffè Broggi in piazza IV Novembre, dal Bar Tripoli in via Cattaneo al CRAL F. Tosi di via Venegoni, fino alla palazzina delle Associazioni d'Arma in Corso Italia.</p>
<p>Tra i pionieri che scrissero le prime pagine della Sezione ricordiamo Bongini, Giuggioloni, Vignati, Garganico e Del Barba, insieme ad altre figure che si distinsero per dedizione come Antononi, Ghilardi, Raffo e Caironi. Un percorso fatto di passione e sacrifici, che nel 1984 trovò casa nei prestigiosi locali della Famiglia Legnanese in via Matteotti, e successivamente presso le Associazioni Sportive Legnanesi in via Milano. Grazie a enormi sforzi economici e alla sempre fattiva collaborazione delle autorità comunali, dopo il passaggio al rinnovato Maniero della Flora in via Ciro Menotti, la Sezione ha infine trovato la sua sistemazione ideale nella palazzina comunale di via Venezia. Qui, in spazi ampi e funzionali, accogliamo oggi oltre centocinquanta associati.</p>
<p>Pur inquadrata nelle direttive del Comitato Nazionale, la Sezione gode di autonomia operativa e amministrativa, ed è guidata da un Presidente eletto fra gli associati e da un Consiglio Direttivo Sezionale da lui nominato. Il nostro impegno quotidiano si declina in numerosi compiti: reclutamento e formazione dei nuovi arbitri, aggiornamento regolamentare e preparazione atletica attraverso lezioni tecniche periodiche e raduni collegiali, gestione e programmazione delle designazioni per conto della FIGC, e amministrazione delle spese sezionali e dei rimborsi.</p>
<p>Ma una Sezione è, prima di tutto, una famiglia. Per questo curiamo con attenzione anche la vita associativa, fatta di cene e pranzi con i nostri cari, tornei di calcio intersezionali e iniziative che rafforzano lo spirito di appartenenza. Da quasi un secolo, la Sezione di Legnano è una palestra di sport, legalità e amicizia: se ami il calcio e vuoi viverlo da una prospettiva unica, la nostra porta è sempre aperta.</p>
""".strip()
